# ===============================
# APPLICATION
# ===============================
spring.application.name=api-gateways
server.port=5555
spring.main.web-application-type=reactive

# ===============================
# EUREKA CONFIGURATION
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# GATEWAY DISCOVERY
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ===============================
# ROUTES (Versioned APIs)
# ===============================

# AUTH SERVICE (Public - No JWT required)
spring.cloud.gateway.routes[0].id=authservice
spring.cloud.gateway.routes[0].uri=lb://AUTHSERVICEJUNE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# BOOKING SERVICE
spring.cloud.gateway.routes[1].id=bookingservice
spring.cloud.gateway.routes[1].uri=lb://BOOKINGSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/booking/**

# PAYMENT SERVICE
spring.cloud.gateway.routes[2].id=paymentservice
spring.cloud.gateway.routes[2].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/payment/**

# USER SERVICE
spring.cloud.gateway.routes[3].id=userservice
spring.cloud.gateway.routes[3].uri=lb://PATIENTSERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/patient/**

# DOCTOR SERVICE
spring.cloud.gateway.routes[4].id=doctorservice
spring.cloud.gateway.routes[4].uri=lb://DOCTORSERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/doctor/**

# ===============================
# GLOBAL CORS CONFIGURATION
# ===============================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*

# ===============================
# LOGGING (Debug)
# ===============================
#logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.cloud.gateway=DEBUG